#!/usr/bin/bash

if [ $( whoami ) == "root" ]; then
    SCRIPT=$( pwd )"/install"
    if [ -e $SCRIPT ]; then
        echo installing...
    else
        echo "Please cd into the correct folder"
        exit 0
    fi
else
    echo Please run as root.
    exit 0
fi

cp -r ./* /srv/http/

chown --recursive http:http /srv/http 
